packetbeat.interfaces.device: any

packetbeat.protocols:
  http:
    ports: [80, 8080, 8000, 8088, 5000, 8002, 18001, 1800]
    # Enabling both request and response capture
    capture_request: true
    capture_response: true
  https:
    ports: [443, 8088]
    # Enabling both request and response capture
    capture_request: true
    capture_response: true

output.elasticsearch:
  hosts: ["http://${SERVER_IP}:9200"]
